version: "3.9"

services:
  housegan_1:
    build: .
    container_name: housegan_1
    ports:
      - "8050:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_1
    restart: always

  housegan_2:
    build: .
    container_name: housegan_2
    ports:
      - "8051:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_2
    restart: always

  housegan_3:
    build: .
    container_name: housegan_3
    ports:
      - "8052:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_3
    restart: always

  housegan_4:
    build: .
    container_name: housegan_4
    ports:
      - "8053:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_4
    restart: always

  housegan_5:
    build: .
    container_name: housegan_5
    ports:
      - "8054:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_5
    restart: always

  housegan_6:
    build: .
    container_name: housegan_6
    ports:
      - "8055:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_6
    restart: always

  housegan_7:
    build: .
    container_name: housegan_7
    ports:
      - "8056:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_7
    restart: always

  housegan_8:
    build: .
    container_name: housegan_8
    ports:
      - "8057:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CONTAINER_ID=housegan_8
    restart: always

